version: '3.1'

services:

  joomla:
    image: joomla
    container_name: joomla    
    restart: unless-stopped
    depends_on:
      - joomladb
    ports:
      - "8200:80"
    volumes:
      - ./html:/var/www/html
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: p4ssw0rd
#      VIRTUAL_HOST: tudominio.com
#      LETSENCRYPT_HOST: tudominio.com

  joomladb:
    image: mysql:8.0
    container_name: joomladb    
    command: --default-authentication-plugin=mysql_native_password  
    expose:
      - "3306"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: joomlapma 
    restart: unless-stopped
    environment:
      PMA_ARBITRARY: "1"
    ports:
      - "8080:80"


##############################################
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
      
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-proxy-letsencrypt
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=info@gmail.com
      - NGINX_PROXY_CONTAINER=nginx-proxy

volumes:
  certs: {}
  vhost.d: {}
